backend:
  name: github
  repo: impulsocreativo/TUO-REPO
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pagine"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {"label": "Titolo", "name": "title", "widget": "string"}
      - {"label": "Contenuto", "name": "body", "widget": "markdown"}
